### ISSUE TITLE
Create a proper design document

### ISSUE THREAD

**Issue by sandrogatti** [sandrogatti/test#1]

**Comment by murphj47** [comment]
It wont allow me to drop it in here for some reason so I had to send it by gmail, thanks!

**Comment by zedr** [comment]
Thanks, John. Could you send it to me, so I can add it?

**Comment by zedr** [comment]
By the way, all contributions should go in the proper project https://github.com/zedr/cs104-as2 . I'm using that one as it is a private project: only us four can see it.

**Comment by murphj47** [comment]
Sorry about that lads,

I will trying to add it last night but the file name wouldn't allow me too .

Thanks
John

**Comment by zedr** [comment]
No probs at all. Awesome job on that document!

**Comment by murphj47** [comment]
Cheers Rigel!

See ye later!
